[package]
name = "courses-web-api"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.102"
arc-swap = "1.9.1"
aws-sdk-s3 = "1.131.0"
axum = "0.8.9"
axum-oidc = { git = "https://codeberg.org/anish/axum-oidc", rev = "c8512b41557f902e061110e4068ec78a564eca80" }
base64 = "0.22.1"
bytes = "1.11.1"
reqwest = { version = "0.13.3", features = ["stream"] }
secrecy = "0.10.3"
secretspec = { version = "0.13.0", default-features = false }
secretspec-derive = "0.13.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.1", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.6.8", features = ["fs", "trace"] }
tower-sessions = "0.15.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
utoipa = { version = "5.4.0", features = ["axum_extras"] }
utoipa-axum = "0.2.0"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
uuid = { version = "1.23.0", features = ["v4", "v7", "serde"] }
