//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "courses")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub course_id: i32,
    pub course_number: String,
    pub dep_id: i32,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub name: String,
    #[sea_orm(column_type = "Double")]
    pub units: f64,
    #[sea_orm(column_type = "JsonBinary")]
    pub prerequisites: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub corequisites: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub unlocks: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub custom_fields: Json,
}

impl ActiveModelBehavior for ActiveModel {}
